package com.ruoyi.business.service.impl;

import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import com.ruoyi.business.domain.BizInsuranceCompany;
import com.ruoyi.business.mapper.BizInsuranceCompanyMapper;
import com.ruoyi.business.service.IBizInsuranceCompanyService;

/**
 * Insurance company service implementation
 */
@Service
public class BizInsuranceCompanyServiceImpl implements IBizInsuranceCompanyService
{
    @Autowired
    private BizInsuranceCompanyMapper companyMapper;

    private final BCryptPasswordEncoder passwordEncoder = new BCryptPasswordEncoder();

    @Override
    public BizInsuranceCompany selectBizInsuranceCompanyById(Long id)
    {
        return companyMapper.selectBizInsuranceCompanyById(id);
    }

    @Override
    public BizInsuranceCompany selectBizInsuranceCompanyByAppKey(String appKey)
    {
        return companyMapper.selectBizInsuranceCompanyByAppKey(appKey);
    }

    @Override
    public BizInsuranceCompany selectBizInsuranceCompanyByUsername(String username)
    {
        return companyMapper.selectBizInsuranceCompanyByUsername(username);
    }

    @Override
    public int updateLoginInfo(BizInsuranceCompany company) { return companyMapper.updateBizInsuranceCompanyLoginInfo(company); }

    @Override
    public int deductBalance(Long companyId, BigDecimal amount)
    {
        return companyMapper.deductBalance(companyId, amount);
    }

    @Override
    public List<BizInsuranceCompany> selectBizInsuranceCompanyList(BizInsuranceCompany company)
    {
        return companyMapper.selectBizInsuranceCompanyList(company);
    }

    @Override
    @Transactional
    public int insertBizInsuranceCompany(BizInsuranceCompany company)
    {
        // AppKey is generated by the company portal after login.
        company.setAppKey(null);
        // Default balance is 0
        if (company.getBalance() == null)
        {
            company.setBalance(BigDecimal.ZERO);
        }
        // Default billing cycle is 30 days
        if (company.getBillingCycleDays() == null)
        {
            company.setBillingCycleDays(30);
        }
        // Default status is normal
        if (company.getStatus() == null || company.getStatus().isEmpty())
        {
            company.setStatus("0");
        }
        // Encode password
        if (company.getPassword() != null && !company.getPassword().isEmpty())
        {
            company.setPassword(passwordEncoder.encode(company.getPassword()));
        }
        return companyMapper.insertBizInsuranceCompany(company);
    }

    @Override
    public int updateBizInsuranceCompany(BizInsuranceCompany company)
    {
        if (company.getPassword() != null && !company.getPassword().isEmpty()
                && !company.getPassword().startsWith("$2"))
        {
            company.setPassword(passwordEncoder.encode(company.getPassword()));
        }
        return companyMapper.updateBizInsuranceCompany(company);
    }

    @Override
    public int deleteBizInsuranceCompanyByIds(Long[] ids)
    {
        return companyMapper.deleteBizInsuranceCompanyByIds(ids);
    }

    @Override
    public int changeStatus(Long id, String status)
    {
        BizInsuranceCompany company = new BizInsuranceCompany();
        company.setId(id);
        company.setStatus(status);
        return companyMapper.updateBizInsuranceCompany(company);
    }

    @Override
    public int updatePassword(Long id, String password)
    {
        BizInsuranceCompany company = new BizInsuranceCompany();
        company.setId(id);
        company.setPassword(passwordEncoder.encode(password));
        return companyMapper.updateBizInsuranceCompany(company);
    }

    @Override
    @Transactional
    public String regenerateAppKey(Long id)
    {
        String appKey = generateUniqueAppKey();
        BizInsuranceCompany company = new BizInsuranceCompany();
        company.setId(id);
        company.setAppKey(appKey);
        companyMapper.updateBizInsuranceCompany(company);
        return appKey;
    }

    /**
     * Generate 32-character AppKey
     */
    private String generateAppKey()
    {
        return UUID.randomUUID().toString().replace("-", "");
    }

    private String generateUniqueAppKey()
    {
        String appKey;
        do
        {
            appKey = generateAppKey();
        }
        while (companyMapper.selectBizInsuranceCompanyByAppKey(appKey) != null);
        return appKey;
    }

}
