<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>ruoyi</artifactId>
        <groupId>com.ruoyi</groupId>
        <version>3.9.2</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ruoyi-business</artifactId>

    <dependencies>
        <dependency><groupId>com.hnchasing.digital.openapi</groupId><artifactId>java-sdk</artifactId><version>1.0.5-SNAPSHOT</version><scope>system</scope><systemPath>${project.basedir}/lib/openapi-sdk.jar</systemPath></dependency>
        <dependency><groupId>com.crcloud.ecsb</groupId><artifactId>ecsb-api-sdk</artifactId><version>1.0.2</version><scope>system</scope><systemPath>${project.basedir}/lib/ecsb-api-sdk-1.0.2.jar</systemPath></dependency>
        <dependency><groupId>com.alibaba</groupId><artifactId>fastjson</artifactId><version>1.2.83</version><scope>system</scope><systemPath>${project.basedir}/lib/fastjson-1.2.83.jar</systemPath></dependency>
        <dependency><groupId>org.bouncycastle</groupId><artifactId>bcprov-jdk15to18</artifactId><version>1.69</version><scope>system</scope><systemPath>${project.basedir}/lib/bcprov-jdk15to18-1.69.jar</systemPath></dependency>
        <dependency><groupId>cn.hutool</groupId><artifactId>hutool-all</artifactId><version>5.8.10</version><scope>system</scope><systemPath>${project.basedir}/lib/hutool-all-5.8.10.jar</systemPath></dependency>
        <dependency><groupId>commons-lang</groupId><artifactId>commons-lang</artifactId><version>2.6</version><scope>system</scope><systemPath>${project.basedir}/lib/commons-lang-2.6.jar</systemPath></dependency>
        <dependency><groupId>com.google.guava</groupId><artifactId>guava</artifactId><version>32.0.0-jre</version><scope>system</scope><systemPath>${project.basedir}/lib/guava-32.0.0-jre.jar</systemPath></dependency>
        <dependency><groupId>org.apache.httpcomponents</groupId><artifactId>httpclient</artifactId><version>4.5.13</version><scope>system</scope><systemPath>${project.basedir}/lib/httpclient-4.5.13.jar</systemPath></dependency>
        <dependency><groupId>org.apache.httpcomponents</groupId><artifactId>httpcore</artifactId><version>4.4.14</version><scope>system</scope><systemPath>${project.basedir}/lib/httpcore-4.4.14.jar</systemPath></dependency>
        <dependency><groupId>commons-codec</groupId><artifactId>commons-codec</artifactId><version>1.14</version><scope>system</scope><systemPath>${project.basedir}/lib/commons-codec-1.14.jar</systemPath></dependency>
        <dependency><groupId>joda-time</groupId><artifactId>joda-time</artifactId><version>2.9.9</version><scope>system</scope><systemPath>${project.basedir}/lib/joda-time-2.9.9.jar</systemPath></dependency>
        <dependency>
            <groupId>com.ruoyi</groupId>
            <artifactId>ruoyi-common</artifactId>
        </dependency>
        <!-- spring-web 用于 HandlerInterceptor -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-webmvc</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
